macro(rti_mcap_find_connext storage)
  if(DEFINED ENV{NDDSHOME})
    list(APPEND CMAKE_MODULE_PATH "$ENV{NDDSHOME}/resource/cmake")
  endif()
  set(_rti_mcap_connext_components core)
  if(${storage})
    list(APPEND _rti_mcap_connext_components recording_service)
    set(_rti_mcap_shared_defined OFF)
    if(DEFINED BUILD_SHARED_LIBS)
      set(_rti_mcap_shared_defined ON)
      set(_rti_mcap_shared_previous "${BUILD_SHARED_LIBS}")
    endif()
    # Service-loaded plugins must share Connext's process-wide runtime state.
    set(BUILD_SHARED_LIBS ON)
  endif()
  set(_rti_mcap_find_options REQUIRED)
  if("${ARGV1}" STREQUAL "PACKAGE")
    set(_rti_mcap_find_options QUIET)
  endif()
  find_package(RTIConnextDDS 7.7.0 EXACT ${_rti_mcap_find_options}
    COMPONENTS ${_rti_mcap_connext_components})
  if(${storage})
    if(_rti_mcap_shared_defined)
      set(BUILD_SHARED_LIBS "${_rti_mcap_shared_previous}")
    else()
      unset(BUILD_SHARED_LIBS)
    endif()
  endif()
endmacro()
